sudo: required

language: bash
services: docker

env:
  - STATSITE_VERSION=0.8.0 VARIANT=alpine

script:
  - ./scripts/cibuild

deploy:
  - provider: script
    script: "scripts/cipublish"
    on:
      repo: azavea/docker-statsite
      branch: master
