#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

set -u

function usage() {
    echo -n \
"Usage: $(basename "$0")
Build container images from templates.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        STATSITE_MAJOR_VERSION="${STATSITE_VERSION:0:3}"
        pushd "${STATSITE_MAJOR_VERSION}"

        sed -e "s/%%STATSITE_VERSION%%/${STATSITE_VERSION}/" \
            "../Dockerfile-${VARIANT}.template" > Dockerfile

        docker \
            build -t "quay.io/azavea/statsite:${STATSITE_MAJOR_VERSION}-${VARIANT}" .

        popd

        ./scripts/test

        docker images
    fi
fi